### PR TITLE
Added Percentage Free Memory Stats

### PR DESCRIPTION
**Pull request by yapyj**
An additional stat variable for us to monitor the percentage of Free Memory.

### CODE REVIEW

**Comment by olivielpeau** [comment]
Hi @yapyj and thanks for this addition! We'll review it shortly.

FYI for this addition to work you'll also need to update this dict: https://github.com/DataDog/dd-agent/blob/5.7.2/checks/collector.py#L309, and on our end we'll have to add the metric to our backend.

**Comment by remh** [comment]
Thanks @yapyj !
We are already collection the % of usable memory as a metric. I'm not convinced that the % of free memory would provide more value.
What do you think ?

**Comment by irabinovitch** [comment]
@yapyj  I was hoping to follow up and get your thoughts regarding Remi's comments.

**Comment by thederby** [comment]
for what it's worth, `1 - sum:system.mem.pct_usable` gives percentage of free memory.

**Pull request closed without merging**
