### PR TITLE
[changelog] Fixing formatting

### PR DESCRIPTION
**Pull request by JohnLZeller**
Currently, the process for getting a link to an older installer is to reach out to support with a particular version. Adding a link to each windows installer version that's already up and public on S3 to the changelog, for users that are reliant on older versions.

I also took this opportunity to fix some of the formatting of the older sections of the changelog, to fit with the newer ones.

### CODE REVIEW

**Comment by JohnLZeller** [comment]
A few things I would like cleared up before we merge.

* Agent 5.2.0 has two MSIs: `ddagent-cli-5.2.0.msi` and `ddagent-cli-5.2.0_win2003.msi`
* Several MSIs are named differently:
 * Agent 5.1.0: `ddagent-cli-5.1.0.MANUAL.msi`
   * There is also a second, that is not public called `ddagent-cli-5.1.0-fix.msi`
 * Agent 5.0.5: `ddagent-cli-5.0.5.582.msi`
 * Agent 5.0.3: `ddagent-cli-5.0.3.578.msi`
 * Agent 5.0.2: `ddagent-cli-5.0.2.576.msi`
* There are 5 MSIs on S3 that we do not allow access to:
 * `ddagent-cli-5.0.1.msi`
 * `ddagent-cli-5.1.0-fix.msi`
 * `ddagent-cli-5.1.1.MANUAL.msi`
 * `ddagent-cli-5.5.0.amd64.msi`
 * `ddagent-cli-5.5.0.msi`
* Many Agent MSIs are not in S3, from what I can tell.

**Comment by JohnLZeller** [comment]
Would you mind taking a look @talwai?

**Comment by degemer** [comment]
@JohnLZeller The `ddagent-cli-5.2.0_win2003.msi` was for Windows 2003 Server (the standard one doesn't work) which is not supported anymore ! (we did maybe one or two custom builds for it)

**Comment by JohnLZeller** [comment]
Remi made the following public:
 * `ddagent-cli-5.0.1.msi`
 * `ddagent-cli-5.1.0-fix.msi`
 * `ddagent-cli-5.1.1.MANUAL.msi`
 * `ddagent-cli-5.5.0.amd64.msi`
 * `ddagent-cli-5.5.0.msi`

**Comment by JohnLZeller** [comment]
@talwai I've added a JSON containing mappings from agent versions to windows installers to the S3: https://s3.amazonaws.com/ddagent-windows-stable/installers.json

The new PR for windows installers is found here: https://github.com/DataDog/dogweb/pull/10650

Would you mind still giving a review for this PR as well? It's just formatting changes now. Should be trivial.

**Comment by talwai** [comment]
:+1:

**Pull request merged**
