### PR TITLE
[tests] split tests/ into two subdirectories

### PR DESCRIPTION
**Pull request by degemer**
Separate agent core tests and all integration tests. I think it looks nicer and cleaner.

It's a WIP for now. I can't/don't want to run all tests locally, so I will fix them once they fail on Travis.

### CODE REVIEW

**Comment by remh** [comment]
:+1:

**Comment by degemer** [comment]
Updated and ready, I added:
- remove unused `run_check` in checks/__init__.py, which was importing
  from tests.common...
- add a Resources class in tests.integrations.common to ease the use of
  fixtures

**Comment by degemer** [comment]
All tests should pass.
Final tree of the `tests/` directory:
```bash
tests
├── checks # tests of checks.d/*
│   ├── integration # contains all real integration tests
│   ├── mock # contains mocked tests
│   └── resources # files needed by tests
└── core # core agent tests
    └── resources # files needed by tests
```

I also added a new `rake` task, `rake test:coverage` which displays untested & mocked tests:
screen shot 2015-04-23 at 15 56 08


These PRs will need a rebase: :cry:
- https://github.com/DataDog/dd-agent/pull/1569 :cry:
- https://github.com/DataDog/dd-agent/pull/1557
- https://github.com/DataDog/dd-agent/pull/1550
- https://github.com/DataDog/dd-agent/pull/1547 :cry: :cry:
- https://github.com/DataDog/dd-agent/pull/1543
- https://github.com/DataDog/dd-agent/pull/1535
- https://github.com/DataDog/dd-agent/pull/1504
- https://github.com/DataDog/dd-agent/pull/1468 :imp: 
- https://github.com/DataDog/dd-agent/pull/1449
- https://github.com/DataDog/dd-agent/pull/1429
- https://github.com/DataDog/dd-agent/pull/1427
- https://github.com/DataDog/dd-agent/pull/1394 :imp: :imp: 
- https://github.com/DataDog/dd-agent/pull/1375
- https://github.com/DataDog/dd-agent/pull/1361 :expressionless: 
- https://github.com/DataDog/dd-agent/pull/1349
- https://github.com/DataDog/dd-agent/pull/1343

**Comment by LeoCavaille** [comment]
Nice! Just a nitpick, I am not a fan of the name `Resources` (I know I used it in `ci/`...) it's a bit confusing and it also refers to the processes snapshots used to create the memory treemaps.
Can we use stubs or fixtures maybe?

**Comment by LeoCavaille** [comment]
LGTM :+1:

**Comment by brettlangdon** [comment]
#1427 and #1543 rebased and tests moved :)

**Comment by degemer** [comment]
Awesome, thanks @brettlangdon !

**Pull request merged**
