### PR TITLE
[wmi] specify fields in queries :rocket:

### PR DESCRIPTION
**Pull request by yannmh**
By default a WMI query will return all the properties of a class in each
instance.
Specify them to avoid any expensive lookups.

### CODE REVIEW

**Comment by JohnLZeller** [comment]
LGTM! :+1: I'd be interested to see how much this speeds things up too. Good idea

**Comment by yannmh** [comment]
Unfortunately I didn't see any noticeable speed or system load improvement... :snail:

**Comment by remh** [comment]
@yannmh we can close this one right ?

**Comment by yannmh** [comment]
Closed in favor of https://github.com/DataDog/dd-agent/pull/2011

**Pull request closed without merging**
