### PR TITLE
[core] add a switch to disable profiling, but still use developer mode

### PR DESCRIPTION
**Pull request by cberry777**
### What does this PR do?

Adds a 'allow_profiling' switch to agentConfig. It defaults to True (the current behavior).
### Motivation

We use 'developer_mode' to monitor our dd-agent, but do not want the added burden of the profiling. It is wise to keep track of what the dd-agent itself is doing (i.e. Watch the watcher!), and 'developer_mode' provides that functionality. The profiling bit is useful only when debugging a new Check. 
### Testing Guidelines

A test is provided: tests/checks/mocks/test_no_profiling.py
### Additional Notes

None

### CODE REVIEW

**Comment by masci** [comment]
Thanks for the code @cberry777 and sorry I'm sooooo late responding!
Could you please add a commented line on the confi file containing the new `allow_profiling` settings and a brief doc about it? 

Thanks!

**Comment by cberry777** [comment]
Done.
Thanks for including this.

**Comment by cberry777** [comment]
BTW: It makes no sense whatsoever that the tests fail now because I added a COMMENT to datadog.conf.example
I think your tests are unstable?

**Comment by cberry777** [comment]
also -- when I run "rake" locally -- all is well>

----------------------------------------------------------------------
Ran 176 tests in 19.761s

OK (SKIP=1)
Cleaning up

**Comment by masci** [comment]
Not your fault, some tests in the CI are extremely flaky, all green!

**Comment by cberry777** [comment]
Hi Massimiliano,

Any way that this one : https://github.com/DataDog/dd-agent/pull/2899  could also make it in??

We are having to extend you agent_metrics.py
And then hack: https://github.com/DataDog/dd-agent/blob/master/checks/__init__.py#L45 with a script.
So it is pretty dirty.
I’d love to remove our hack

I do think others will also like this addition!
I allows us to build some great dashboards of dd-agent in action.

THANKS,
-- Chris

**Pull request merged**
