### PR TITLE
Add timeout and whitelists to couchdb check, and improve the CI.

### PR DESCRIPTION
**Pull request by hkaj**
This adds the installation of couch in the CI (no need to install manually anymore).
It also limits the check to 50 DB, and adds whitelist and timeout features, both configurable in the yaml.

### CODE REVIEW

**Comment by hkaj** [comment]
Integration fails because of missing headers, will fix this shortly.

**Comment by LeoCavaille** [comment]
@hkaj finally got it pushed and running, could you do a quick last review before I merge this?

**Comment by hkaj** [comment]
Looks good to me. :beers:

**Comment by LeoCavaille** [comment]
Thanks, cheers :beer:

**Pull request merged**
