### PR TITLE
[docker] Add hierarchical_memory_limit and hierarchical_memsw_limit cgroup metrics to be collected (as optional) from Docker

### PR DESCRIPTION
**Pull request by agassner**
Related to https://github.com/DataDog/dd-agent/issues/1739

### CODE REVIEW

**Comment by agassner** [comment]
It seems that the build failure is not related to the changes in this PR.

**Comment by remh** [comment]
Thanks a lot @agassner for this!
I actually a work in progress scheduled for our Agent 5.5.0 to add these metrics. In addition we'll also compute a usage % that can be used with monitors. So i'm going to close this PR. 

Thanks again for your contribution!

**Comment by agassner** [comment]
No problem @remh thanks for that!

**Comment by remh** [comment]
@agassner FYI this is the PR: https://github.com/DataDog/dd-agent/pull/1908

**Comment by agassner** [comment]
@remh Nice one, thanks!

**Pull request closed without merging**
