### PR TITLE
SqlServer integration extended to call custom proc to return metrics

### PR DESCRIPTION
**Pull request by rlaveycal**
This replaces #2328 by integrating the logic into the SqlServer integration.

A custom proc can be called to return metrics. Optional guard conditions can be set to support running in a HA environment (only get metrics from the active DB instance). Missing databases can also be ignored to simplify config deployment.

### CODE REVIEW

**Comment by truthbk** [comment]
@rlaveycal very much appreciated, we will review this soon.

**Comment by truthbk** [comment]
@rlaveycal our apologies for leaving this one in the backburner for too long! Unfortunately in that time some conficts have cropped up. Could you please rebase this? Thank you!

**Comment by rlaveycal** [comment]
@truthbk Hopefully I've rebased it properly

**Comment by olivielpeau** [comment]
@rlaveycal looks like your rebase didn't work as expected, could you give us permissions to push on your branch so that we can try and fix it? Thanks!

**Comment by rlaveycal** [comment]
Do you need me to rebase this to move it along?

**Comment by masci** [comment]
@rlaveycal I'd really like to merge your code into the check but the current state of your branch makes it extremely difficult. Ideally the PR should contain only your commits.
I know I'm asking a lot but could you open another PR on the integrations-core repo at https://github.com/DataDog/integrations-core containing only the relevant commits?

I'm glad to help if you need assistance, likely is just a matter of cherry picking your commits one by one on a clean branch in the new repo.

Sorry for the trouble!

**Pull request closed without merging**
