### PR TITLE
[process] Improve sampling of cpu.pct

### PR DESCRIPTION
**Pull request by olivielpeau**
See https://github.com/DataDog/dd-agent/issues/1660

Improvements:
- Non-blocking call to `cpu_percent` after the first sample
- After the first sample, retrieves an averaged value since the last call (instead of an averaged value over the fraction of a second defined by `cpu_check_interval`)

The first sample of `cpu.pct` on every process still uses a blocking call so that the check can retrieve a value as soon as it finds new processes. Setting the `cpu_check_interval` to `0` removes that first blocking call.

Also fixed the handling of the cache of AccessDenied PIDs (it was previously refreshed at every run of every instance).

### CODE REVIEW

**Comment by yannmh** [comment]
> Setting the cpu_check_interval to 0 removes that first blocking call.

As we discussed, I think that's the right thing to do.

**Comment by olivielpeau** [comment]
Thanks @yannmh for the review!

I've implemented the changes you suggested (see commit message of my last commit: da212b8).

**Comment by yannmh** [comment]
Nice improvement. Looks good to merge to me ! :ship:

**Comment by olivielpeau** [comment]
Thanks again for the thorough review ;)

I've rebased the PR and changed the Exception type tested in `test_ad_cache` (per your comment), I'll merge once the CI passes.

**Comment by olivielpeau** [comment]
The CI is failing on unrelated tests, merging.

**Comment by remh** [comment]
:+1:

**Pull request merged**
