### PR TITLE
[openstack] Missing verify=self._ssl_verify in two calls to _make_request_with_auth_fallback

### PR DESCRIPTION
**Pull request by jcejohnson**
### What does this PR do?

Fixes missing verify=self._ssl_verify in two calls to _make_request_with_auth_fallback
### Motivation

We use self-signed certs. 'info' was reporting CERTIFICATE_VERIFY_FAILED errors when trying to get project stats even with 'ssl_verify: false' in conf.d/openstack.yml
### Testing Guidelines

An overview on [testing](https://github.com/DataDog/dd-agent/blob/master/tests/README.md)
is available in our contribution guidelines.
### Additional Notes

Anything else we should know when reviewing?

The call at line 661 (in function get_stats_for_single_project) fixed my immediate issue. I modified the call at line 846 (in function get_scoped_project) because that was the only other call not having the verify parameter.

### CODE REVIEW

**Comment by olivielpeau** [comment]
Thanks @jcejohnson for fixing this!

If you have some time, could you actually pass `verify=self. _ssl_verify` directly to the `requests.get` call in `_make_request_with_auth_fallback`, since the `verify` should always be set to `self. _ssl_verify`? (https://github.com/DataDog/dd-agent/blob/5.9.1/checks.d/openstack.py#L378) And remove the verify parameter from `_make_request_with_auth_fallback` altogether.

The appveyor tests have been fixed on the current master, you can rebase your branch on top of it to make appveyor pass.

Thanks again, let me know if you have any questions

**Comment by jcejohnson** [comment]
Done!
I modified the signature of _make_request_with_auth_fallback to remove the verify parameter and have it directly pass verify=self._ssl_verify to requests.get() as you suggested.

**Comment by olivielpeau** [comment]
@jcejohnson Thanks! Looks like your branch includes a lot of changes that are not relevant to your PR though. Could you rebase your branch o the current master and add only your relevant commits to it?

Apparently I'm able to push on your branch so I can probably take care of this too, let me know :)

**Comment by jcejohnson** [comment]
Yea, those all came in when I rebased to the current master.

**Comment by olivielpeau** [comment]
@jcejohnson Hmm something must have gone wrong, I'll give it another try and push to the `bugfix-openstack-ssl` branch of your fork

**Comment by olivielpeau** [comment]
Pushed to your branch, the diff looks cleaner now and the changes are good to go

Merging, thanks @jcejohnson!

**Pull request merged**
