### PR TITLE
IBM Websphere MQ integration

### PR DESCRIPTION
**Pull request by rlaveycal**
This is an integration foe IBM Websphere MQ, written on Windows and MQ 7.0.1. It uses the command line so should work on other versions/platforms

This is a re-submission of a previous pull request as I had my local branching all wrong (Git newby)

### CODE REVIEW

**Comment by remh** [comment]
Thanks a lot @rlaveycal  our set of new features is frozen for our 5.2.0 release.

We'll review for our 5.3. release.
Thanks again!

**Comment by irabinovitch** [comment]
@rlaveycal Apologies for the delay here.  Have you been using this internally? We'd love to hear how it is working for you. In the mean time, it would also be good to look into why tests are failing at the moment.

**Comment by rlaveycal** [comment]
@irabinovitch yes this has been running in our production environment without problems for the last year. We use MQ 7.0 and 7.5 on Windows but it should work with 8.0 and other platforms as it uses the command line tools.

**Comment by irabinovitch** [comment]
@rlaveycal Thanks for the update. Were you by any chance able to check why tests are failing on this change?

**Comment by irabinovitch** [comment]
We would love to include this check, but would need your help in addressing the failing tests. For now we're going to close the PR but please do re-open when you have the bandwidth to review the tests.

**Pull request closed without merging**
