### PR TITLE
Apply image_repository tag to docker.containers.*

### PR DESCRIPTION
**Pull request by optimality**

### CODE REVIEW

**Comment by remh** [comment]
Thanks a lot @optimality !
@hkaj @JohnLZeller can you have a look please ?

**Comment by yannmh** [comment]
Thanks a lot for your contribution @optimality.

We addressed this request in a previous PR #1691. It'll be part of the next agent released planned for mid August. Thanks again.

**Comment by optimality** [comment]
This is a different feature.  This is intended to apply the `image_repository` tag to `docker.containers.running` and `docker.containers.stopped`, which don't currently have that tag.  The PR you referenced applies that tag to `docker.mem.*` and `docker.cpu.*`.

This feature will let us add running/stopped counts to our service dashboards, which we can't currently do.

**Comment by yannmh** [comment]
Sorry for the confusion @optimality  :blush:, I am reopening the PR. @JohnLZeller will review it shortly.

**Comment by optimality** [comment]
Thanks!  I can totally see how it looks just like #1691 at first glance :smile_cat:.

**Comment by remh** [comment]
@optimality I'm closing this pull request. The docker check is being rewritten, so i'll make sure that this feature will be part of it.

**Comment by optimality** [comment]
Cool, looking forward to the new version.

**Pull request closed without merging**
