### PR TITLE
[tests] switch lighttpd check to AgentCheckTest.

### PR DESCRIPTION
**Pull request by hkaj**

### CODE REVIEW

**Comment by LeoCavaille** [comment]
You removed the test with the instance `?auto` URL, was it just not useful or redundant?

**Comment by hkaj** [comment]
@LeoCavaille it's redundant. The check adds the ?auto automatically in the first config after trying without it and failing to parse the result.

**Comment by hkaj** [comment]
Also the 3 build failures in Travis are due to timeouts.

**Comment by LeoCavaille** [comment]
nice :+1:

**Pull request merged**
