### PR TITLE
RFC: Kubernetes: Add cpu and memory requests, limits, and capacity info.

### PR DESCRIPTION
**Pull request by markine**
# An RFC: first cut of code, looking for green light for further cleanup. Also seeking any guidance on testing from authors of the kubernetes Check code.

### What does this PR do?

Add reporting of Kubernetes resource management info: CPU and memory requests, limits, and capacity.

### Motivation

Monitoring of cluster resources from a scheduling/allocation perspective is important. E.g. over-allocation of CPU resources to deployments may cause pod scheduling failures even if actual CPU usage in the cluster is low. We want to get ahead of these errors by monitoring request/limit/capacity data in DataDog.

### Testing Guidelines

An overview on [testing](https://github.com/DataDog/dd-agent/blob/master/tests/README.md) is available in our contribution guidelines.

### CODE REVIEW

**Comment by irabinovitch** [comment]
Thanks @markine.  We've got a number of pending Kubernetes PRs that this should fit in nicely with! 

I'm copying @hkaj  and @masci here since they've been focused on the k8s checks and might have more targeted comments/feedback.

**Comment by masci** [comment]
Hi @markine and thanks for your contributions!
Part of the check is under refactoring in #2551 where `limits` and `requests` metrics were also added, can you take a look at it and rebase your changes on it?
We're positive to ship it with the upcoming `5.9`.

**Comment by masci** [comment]
Heads-up, #2551 was merged on `master`, ready to be shipped with 5.9

**Comment by therc** [comment]
#2551, unfortunately, does not parse suffixes like this PR does:

https://github.com/DataDog/dd-agent/pull/2766/files#diff-aaca1c420c7db1243eed5319a61627deR330

Is this PR going to be rebased?

**Comment by irabinovitch** [comment]
@markine When you have a moment please rebase your changes on master. Thanks!

**Comment by markine** [comment]
@irabinovitch I may be able to get some cycles for this in the coming weeks. Stay tuned. Thanks!

**Comment by markine** [comment]
@irabinovitch @masci @therc 

I've rebased this PR in https://github.com/DataDog/dd-agent/pull/2935. Closing this PR.

**Pull request closed without merging**
