### PR TITLE
[apache] fix tests

### PR DESCRIPTION
**Pull request by yannmh**

### CODE REVIEW

**Comment by LeoCavaille** [comment]
Looks like it's waiting for some access on Apache threads to return something, so maybe if you stimulate it before testing, this metric will always be here?
See https://github.com/apache/httpd/blob/trunk/modules/generators/mod_status.c#L342-L346

Also this is not cool as it will break the coverage report if the metric is there but isn't tested.

**Comment by yannmh** [comment]
Does not seem to solve the issue :disappointed:

**Comment by LeoCavaille** [comment]
Have you tried hitting the default apache URL instead of the status URL? like `http://localhost:1234`

**Comment by yannmh** [comment]
@LeoCavaille Looks good to merge to me

**Comment by LeoCavaille** [comment]
Thanks!

**Pull request merged**
