### PR TITLE
[cloud metadata] Fail on non 2xx responses

### PR DESCRIPTION
**Pull request by remh**
### What does this PR do?

To keep the same behavior as before we need to make sure not to put bad
data in the metadata if the metadata endpoint returns a non 2xx
response code (that was already the case with urllib)

This fixes a bug that was introduced with https://github.com/DataDog/dd-agent/pull/2822

### Testing Guidelines

Confirmed that it fixed the issue i saw on Google Compute nodes.

### CODE REVIEW

**Comment by truthbk** [comment]
This looks good. You don't want to log anything so that it fails less silently?

**Comment by remh** [comment]
I can log something in debug, but in all cases some of these calls are expected to fail. I'll add something in debug. Thanks for the feedback

**Comment by remh** [comment]
@truthbk done

**Comment by truthbk** [comment]
Nice! :shipit:

**Pull request merged**
