### PR TITLE
[mysql] Add table_size_metrics, tags: schema, table

### PR DESCRIPTION
**Pull request by LaurentKol**
Monitor schema size at table level.

_information_schema.tables_ has table granularity information, querying table size isn't significantly more expensive according to our testing.

We considered adding an extra tag to _schema_size_metrics_ but that might not have been good for people with too many tables or people who just don't need that granularity, this is an extra metric for those who needs table level size.

### CODE REVIEW

**Comment by truthbk** [comment]
@LaurentKol this probably makes a lot of sense to include, and thank you for creating a feature flag for it (it'll help for users that aren't interested and want to avoid the overhead). You have some pylint issues in your changes. Could you take a look and fix them? 😃  

Thanks a bunch!

**Comment by LaurentKol** [comment]
@truthbk thanks, done :smiley:

**Comment by LaurentKol** [comment]
I closed this pull-request because I don't expect to have more commits, but was I supposed to leave it open until it gets merged?

**Comment by olivielpeau** [comment]
@LaurentKol: thanks for the heads up, actually you should leave the PR open (otherwise we'll think the PR is not relevant anymore). Let me re-open it now :)

We'll spend some time to review your changes for the next minor release of the agent, thanks!

**Comment by olivielpeau** [comment]
Actually the merge window for `5.10.0` will close real soon and I don't think we'll have time until then to get this PR through a full review cycle. I'll move this to the Triage milestone until we can review it.

Sorry about that @LaurentKol, we'll update you soon

**Comment by masci** [comment]
Make sure to make a statement this feature might impact billing (extra metrics would be considered custom)

**Comment by masci** [comment]
@LaurentKol sorry for the late response.

Are you still up with merging this fix? In case please let me know, I can migrate this PR to `integrations-core`. Thanks!

**Comment by masci** [comment]
Closing for inactivity, feel free to reopen at any time!

**Pull request closed without merging**
