### PR TITLE
Add tags to Elasticsearch events

### PR DESCRIPTION
**Pull request by garnermccloud**

### CODE REVIEW

**Comment by elafarge** [comment]
@garnermccloud Just reviewed. Good to go :)

**Comment by LeoCavaille** [comment]
@elafarge please rebase this PR on master and re-run the test suite (runs it on 5 different versions of ES).

**Comment by elafarge** [comment]
Done

**Comment by LeoCavaille** [comment]
@elafarge I might be wrong, but where are `self.config` and `self.curr_config` defined?
Looks like the code is still using the old implementation of the check :/ ?

**Comment by elafarge** [comment]
You're not wrong. My bad. I'm rather surprised it went through our pylint check though 0_o

**Comment by LeoCavaille** [comment]
:+1:

**Pull request merged**
