### PR TITLE
Updating psutil to 3.3.0

### PR DESCRIPTION
**Pull request by truthbk**

### CODE REVIEW

**Comment by truthbk** [comment]
relevant doc: https://github.com/giampaolo/psutil/blob/master/HISTORY.rst

**Comment by talwai** [comment]
@truthbk the default configuration for agent_metrics collection will also need an update: https://github.com/DataDog/dd-agent/blob/master/conf.d/agent_metrics.yaml.default

**Comment by truthbk** [comment]
@talwai thanks for the comment, fixed accordingly. We've now tested both the windows and linux agents with the updated version.

**Comment by olivielpeau** [comment]
:+1:

Let's remember to upgrade psutil on our windows build VMs.

**Pull request merged**
