### PR TITLE
[docker_daemon] add docker storage driver metrics

### PR DESCRIPTION
**Pull request by patrickbcullen**
Added the docker storage driver metrics for the devicemapper storage driver (used by CentOS/RHEL) using the docker info API.

The unit test shows the metrics names which are patterned after the system.disk.* metrics.

### CODE REVIEW

**Comment by remh** [comment]
Thanks a lot @patrickbcullen 
We'll review this for 5.8.0
One concern i have is that in my experience i have noticed that in some cases the info command can take while to return. Have you experienced that kind of issue ?

**Comment by patrickbcullen** [comment]
The info command takes 300-700 milliseconds on my system. Is that too long? Also how do I rerun the checks? It looks like my build failed on an unrelated test.

**Comment by irabinovitch** [comment]
@patrickbcullen  I've re-triggered the tests.

**Comment by patrickbcullen** [comment]
I found the cause of the test failure. It appears that collections.Counter is only supported in Python 2.7 and the Travis tests run in Python 2.6 (see http://stackoverflow.com/questions/10099013/importerror-cannot-import-name-counter).

I did not add the import code to dd-agent/checks.d/docker_daemon.py, but I was the first person to add a mocks test for it which is why the error shows up with this pull request.

Suggestions on how to handle this? Apparently docker_deamon only works on Python 2.7 and later now anyways so maybe the Travis tests should be upgraded to Python 2.7.

**Comment by remh** [comment]
Thanks a lot @patrickbcullen you are right.
It was not an issue as no one is running the Docker Daemon check on python 2.6.
I think the easiest way to fix that would be to switch from `Counter` to a `defaultdict(int)` on these two lines.
Given how we use the Counter that would be the easiest way.
Can you take a pass at it while you're at it ?
Thanks a lot!

**Comment by patrickbcullen** [comment]
It looks like you cannot write mock tests for docker_daemon.py since it was never designed to be tested in that way. I am not sure how to proceed with getting this pull request approved since I don't want to rewrite docker_daemon.py. I will just keep this change in my fork for now.

**Comment by hkaj** [comment]
Closing as we already collect those. I think there was concurrent work going on when you opened this PR. Thank you anyway for the contribution!

**Pull request closed without merging**
