### PR TITLE
Add Fail2ban check

### PR DESCRIPTION
**Pull request by brettlangdon**
New PR from closed #1427

Add a fail2ban check, which reports stats from `fail2ban-client status <jail>`

### CODE REVIEW

**Comment by JohnLZeller** [comment]
If possible, could we refactor this check to use get_subprocess_output from utils.subprocess_output? We're refactoring the agent to use this wherever we can, to avoid errors that come up when a subprocess hangs from a full `subprocess.PIPE`

**Comment by brettlangdon** [comment]
Hey @JohnLZeller, yeah, I can make that change, should be easy enough.

I was also thinking about this check a little more recently, another option might be just to watch the `/var/log/fail2ban.log` to grab when it blocks/unblocks an ip. However, this log is owned by `root/adm` on my machine, so `dd-agent` wont be able to read from it anyways :(

**Comment by gmmeyer** [comment]
Hi @brettlangdon,

Thanks again for your contribution, always very much appreciated. We're currently transitioning our checks to a new SDK-based model for the agent. An unfortunate side-effect is that we have to impose a freeze on the dd-agent repo. 

The SDK consists of two repositories https://github.com/DataDog/integrations-core and https://github.com/DataDog/integrations-extras, where all of our checks will reside. This PR would belong in the extras repository. 

Would you be so kind as to re-open the PR there? 

We have facilitated some tools to help you with the SDK development that should help you get up and running in no time: [sdk guide](http://docs.datadoghq.com/guides/integration_sdk/) [datadog sdk gem]( https://github.com/DataDog/datadog-sdk-testing). We are very sorry for the inconvenience caused. 

Thank you for your patience as we make this transition!

**Comment by gmmeyer** [comment]
We're going to keep this open for now, we'll port this over on a branch to the [integration extras](https://github.com/DataDog/integrations-extras) repo. You can take it from there once that work has completed and we can close this then.

**Comment by truthbk** [comment]
Hi @brettlangdon, since the transition to the SDK has begun I have taken the liberty to open a PR with your work here: DataDog/integrations-extras#37. You authorship should be preserved.

This should hopefully ease the pain of transitioning to the SDK. Let me know if you have any questions.

**Comment by irabinovitch** [comment]
@brettlangdon  Would it be OK if we close this PR and track further efforts at https://github.com/DataDog/integrations-extras/pull/37 ?  

We will be keeping a close eye on these repos and will be able to offer  much quicker feedback on any PRs you submit. Additionally we have launched a new [community office hours](https://github.com/DataDog/dd-agent/wiki/Community-Office-Hours) during which our engineering and community teams will be available to perform code review and offer feedback on new and existing integration.

**Comment by brettlangdon** [comment]
:+1:

**Comment by irabinovitch** [comment]
Thanks @brettlangdon.  Join us at [office hours](https://github.com/DataDog/dd-agent/wiki/Community-Office-Hours) if we can help with anything on the PR front.

**Pull request closed without merging**
