### PR TITLE
SqlProc integration

### PR DESCRIPTION
**Pull request by rlaveycal**
This integration calls a stored procedure to return a custom set of metrics from the database. It is based on the sqlserver integration and so uses SQLOLDDB for database access. It is thus tied to Windows but I'm sure could be made cross-platform if a suitable API were used (ODBC?).

As well as running a proc the integration can be configured to use an ``` only_if ``` guard condition. This allows deployment to backup servers but for metrics to be captured only when they become active.

### CODE REVIEW

**Comment by olivielpeau** [comment]
Hi @rlaveycal, and thanks for this addition!

Given that each SQL check is very specific to the DBMS it integrates with, and that we don't have plans to have a common base for all the SQL checks I think this feature should be added directly to the existing SQLServer check.

We could then work on porting the feature to other DBMSes if there's demand for it.

What do you think?

**Comment by irabinovitch** [comment]
@rlaveycal Hey! Thanks again for this contribution to the SQL integration.  Do you have any thoughts regarding moving this to the core SQL integration?

**Comment by rlaveycal** [comment]
@irabinovitch Hi, your suggestion makes sense. Will try and find some time to refactor.

**Comment by rlaveycal** [comment]
Superseded by #2445

**Pull request closed without merging**
