### PR TITLE
[Script] Fix package installation validation

### PR DESCRIPTION
**Pull request by remh**
Before that, if the forwarder was not in a ready state at the first
try, the installation script would fail directly without trying a few
more times as we used a trap on error and set -e.

This commit clears the trap and use set +e to allow a few failures for
the status verification.

### CODE REVIEW

**Comment by remh** [comment]
@LeoCavaille can you review please ? it's making a few automated tests to fail.

**Comment by remh** [comment]
going to refactor a bit to avoid the duplication of the trap restoration

**Comment by LeoCavaille** [comment]
OK let me know when I can review.

**Comment by remh** [comment]
Ready for review @LeoCavaille

**Comment by LeoCavaille** [comment]
Thanks, looking good. Merging.

**Pull request merged**
