### PR TITLE
[riak] updated checks and test for 2.0 LTS

### PR DESCRIPTION
**Pull request by jcapricebasho**
### What does this PR do?

This PR updates the statistics collected by the riak.py dd-agent check for the Riak 2.0 LTS release, with the corresponding gauges added to test_riak.py. Additionally, a `min_collection_interval` of `60` was added to riak.yaml.example, as most Riak statistics are calculated on a per-minute sliding window.
### Motivation

The riak.py check was missing new metrics added in Riak 2.0 that allow more fine grained monitoring of throughput and latencies, monitoring of Riak Data Types, and monitoring of Riak Search.
### Testing Guidelines

All stats in riak.py have corresponding gauges in test_riak.py. Riak Search checks, and checks that return "undefined" instead of 0 have been omitted (added to CHECK_NOT_TESTED).

### CODE REVIEW

**Comment by gmmeyer** [comment]
Thank you very much for your contribution, @jcapricebasho! 😄 

We'll get around to reviewing it soon and offer you more feedback. In the meantime, you should address the failing tests on Travis.

**Comment by irabinovitch** [comment]
@jcapricebasho Any sense of whats going on with the tests?

**Comment by jcapricebasho** [comment]
@irabinovitch Ilan, the Travis builds were failing due to trailing whitespace in a comment and a missing new line at the end of the file. All tests are passing now.

**Comment by irabinovitch** [comment]
@jcapricebasho As of Datadog 5.9 we are no longer integration on this repo and instead redirecting them to datadog/integrations-core and integrations-extras. I think this one likely fits in integrations-extras.

Examples of the new format are available in this document:
http://docs.datadoghq.com/guides/testing/

**Comment by irabinovitch** [comment]
@jcapricebasho We'd love to include this in 5.10. Do you think you'll have a chance to review the packaging feedback?

**Comment by gmmeyer** [comment]
Hey @jcapricebasho I wanna merge this before our transfer over to the sdk. I can't push to your branch, can you fix the merge conflict on this? My comments before were nits to help better organize the metrics within our app, but I think they're largely unnecessary changes and, on further reflection, they have the potential to be breaking changes since they might be changing the metric names. So, don't worry about them.

If you just copy and paste this as your conf.d/riak.yaml.example, it'll fix it:

```
init_config:

instances:
  - url: http://127.0.0.1:8098/stats
    min_collection_interval: 60
    # cacert: /path/to/ca.pem
    # disable_cert_verify: false
    # tags:
    #  - optional_tag1
    #  - optional_tag2
```

Since we wanna get the SDK out soon, I can just make these changes myself and merge it on a separate branch if you'd like.

**Comment by gmmeyer** [comment]
This was superseded by #3189 and the changes have been merged into master.

**Pull request closed without merging**
