### PR TITLE
add unbound dns caching resolver support

### PR DESCRIPTION
**Pull request by joewilliams**
### What does this PR do?

This adds support for unbound DNS caching resolver. http://unbound.net/
### Motivation

We need the metrics.

### CODE REVIEW

**Comment by irabinovitch** [comment]
@joewilliams Thanks for the contribution. We are in the process of finalizing the 5.9 release so we may be delayed in reviewing this.  In the mean time, I noticed style checks were failing on the following:

./checks.d/unbound.py:2:1: F401 'os' imported but unused
./checks.d/unbound.py:7:1: F401 '_is_affirmative' imported but unused
./checks.d/unbound.py:8:1: F401 'Platform' imported but unused

**Comment by masci** [comment]
Hi @joewilliams,

Thanks again for your contribution, always very much appreciated. We're currently transitioning our checks to a new SDK-based model for the agent. An unfortunate side-effect is that we have to impose a freeze on the dd-agent repo. The SDK consists of two repositories https://github.com/DataDog/integrations-core and https://github.com/DataDog/integrations-extras, where all of our checks will reside. This PR would belong in the core/extras repository. Would you be so kind as to re-open the PR there? We have facilitated some tools to help you with the SDK development that should help you get up and running in no time: [sdk guide](http://docs.datadoghq.com/guides/integration_sdk/) [datadog sdk gem]( https://github.com/DataDog/datadog-sdk-testing). We are very sorry for the inconvenience caused. 

Thank you for your patience as we make this transition!

**Comment by truthbk** [comment]
@joewilliams, @masci and I, we've taken the liberty of opening a PR here to help you transition to the SDK DataDog/integrations-extras#41

We created a patch with your work and dropped it that PR. Please feel free to continue your work there. 🙇

**Comment by irabinovitch** [comment]
Hi @joewilliams, Would it be OK if we close this PR and track further efforts in https://github.com/DataDog/integrations-extras/pull/41 ?

We're currently in the process migrating agent checks out this repo and into new https://github.com/DataDog/integrations-core and https://github.com/DataDog/integrations-extras repos. This change would fit into the https://github.com/DataDog/integrations-extras repo where @masci  and @truthbk have migrated your PR.

We'd appreciate your help in addressing the minor comments on this PR so that we can merge and release your contribution.

To offer some background the reason we're moving checks into seperate repos is to allow us to release new checks such as yours here independently of the agent.  This will allow us to merge/test them more quickly and offer you quicker feedback.

Some background on this is available at:
- [SDK guide](http://docs.datadoghq.com/guides/integration_sdk/) 
- [datadog SDK gem]( https://github.com/DataDog/datadog-sdk-testing). 

If you have any questions, we are happy to discuss here in this PR or on [Slack](http://chat.datadoghq.com) in #integrations. 

Also I realize it is short notice but our next [community office hours and code review](https://github.com/DataDog/dd-agent/wiki/Community-Office-Hours) is today at 10:30am PT and we'd be happy to review a PR with you there if you'd like to join us.  The next one will be in 2 weeks.

**Comment by joewilliams** [comment]
@irabinovitch sounds good.

**Comment by remh** [comment]
Closing in favor of https://github.com/DataDog/integrations-extras/pull/41

**Pull request closed without merging**
