### PR TITLE
Aerospike Plugin for Datadog

### PR DESCRIPTION
**Pull request by PratikJarande-GSLab**
Hi,

We have made changes in our Aerospike plug-in in accordance with the changes in Dog API. So creating a new pull request.

Regards,

Pratik

### CODE REVIEW

**Comment by irabinovitch** [comment]
@PratikJarande-GSLab Thank you for the contribution. Our team will take a look. In the mean time, have you had a chance to look into the failing tests here?

**Comment by irabinovitch** [comment]
@PratikJarande-GSLab  Hope all is well. Did you have a chance to review the failing tests?

**Comment by PratikJarande-GSLab** [comment]
Hi Ilan,

I have gone through the failing tests mentioned above and I'd want to
rectify them. However, i find it difficult to understand the nature of
errors that are raised by the tests.

For example, I'm facing this issue in the *continuous-integration/travis-ci/pr
**#6982.1* check*,* and I'm not able to figure out what exactly is
expected, following is the extract from the error log file that was
generated from the tests,

./checks.d/aerospike.py:14:1: I100 Imports statements are in the wrong
order. from aerospike should be before from aerospike
./checks.d/aerospike.py:15:1: I100 Imports statements are in the wrong
order. from aerospike should be before from aerospike

If you could help me with understanding the errors that'd be really
helpful. Also it'd be great if you could share the conditions in which
travis test fails and succeeds. It'll help me in achieving the correct
solution for the code.

Thanks and Regards,
Pratik Jarande


On Thu, Jul 30, 2015 at 12:28 AM, Ilan Rabinovitch <notifications@github.com

**Comment by PratikJarande-GSLab** [comment]
Hi Ilan,

A gentle reminder for the failing travis test issue.

Thanks and Regards,
Pratik Jarande

**Comment by PratikJarande-GSLab** [comment]
Hi Ilan,

A gentle reminder for the failing travis test issue.

Thanks and Regards,
Pratik Jarande

**Comment by irabinovitch** [comment]
You might try running flake8 locally against your changes.  It mostly appears to be failing on unused imports or import ordering. Those should be fairly quick to clean up.

I believe Will has also been in touch with your team directly via email on a few items.  Lets definitely circle up via email soon.

**Comment by PratikJarande-GSLab** [comment]
Hi Ilan,

As suggested, I've used flake8 to resolve the unused imports and import
ordering issues. Also, I've attached a snapshot of the errors that i
encountered using flake8. For import order style, I used the google style
over the cryptography one. I hope it is in accordance with import order
style check of the Travis test.

I have committed the changes in git, do i need to send a new pull request
or the existing one would do fine ?

And yes, we're in touch with Will on the integration process.

Thanks and Regards,
Pratik

**Comment by irabinovitch** [comment]
@PratikJarande-GSLab  A new PR shouldn't be needed. Were you by any chance able to connect with Will?

**Comment by PratikJarande-GSLab** [comment]
Hey Ilan,

Can i know by when my pull request will be merged? And no, we were not able
to connect with Will for sometime now.

Thanks,
Pratik

**Comment by joshk0** [comment]
So, I was about to borrow the code from this PR for my own purposes while the DataDog folks demurred, but...

This integration looks a little odd to me. Why are whole dashboards being published rather than individual metrics?

Not everyone wants the pre baked dashboards, and it sort of breaks the abstraction of the Agent to have it not just submit the low level information.

My expectation was that it would behave much like the [haproxy check](https://github.com/DataDog/dd-agent/blob/master/checks.d/haproxy.py): It would collect low level stats on clustering, latency and namespaces, and report a service check.

**Comment by irabinovitch** [comment]
@PratikJarande-GSLab Please get in touch with Will Xu. I believe hes speaking with your colleagues about next steps here.

**Comment by PratikJarande-GSLab** [comment]
@joshk0 The pre baked dashboards are for the sake of user's convenience and the user can make custom dashboards from the individual metrics that are being pushed if he so wishes.

**Comment by PratikJarande-GSLab** [comment]
@irabinovitch We tried to get in touch with Will Xu but it's been quite a while now that he has not replied back.

**Comment by irabinovitch** [comment]
@PratikJarande-GSLab  Feel free to add me to the thread my firstname @datadoghq.com. I'll be happy to follow up.

**Comment by irabinovitch** [comment]
@PratikJarande-GSLab  With regards to the dashboards, as others have mentioned making these calls from within an AgentCheck is not ideal.  This should ideally be done by the "install" button on the integration tile.

**Comment by irabinovitch** [comment]
We are going to close this in favor of the work being done by @joshk0  in #2219.  Thanks to @joshk0  for stepping in and addressing the feedback!

**Pull request closed without merging**
