### PR TITLE
[core] Set agent pid file and path from constant

### PR DESCRIPTION
**Pull request by urosgruber**
I'm working on FreeBSD port for dd-agent and I notice PID_FILE constant not being used. I also add option to set a path for pid file. I can change PID_DIR to '/tmp' and update to correct dir in FreeBSD port.

### CODE REVIEW

**Comment by remh** [comment]
Thanks @urosgruber can you squash your commits into one please ?

**Comment by irabinovitch** [comment]
@urosgruber Hey, we're starting to lock down the CHANGELOG for 5.7. I'd love to see this included. Can you take a look at @remh 's feedback?

**Comment by urosgruber** [comment]
I can make it first thing in the morning (CET)

**Comment by urosgruber** [comment]
@irabinovitch let me know if everything ok.

**Comment by remh** [comment]
@urosgruber Looks like the tests are failing. Can you rebase with the master branch ? This should get the tests to pass. 
We'll merge after.
Thanks!

**Comment by urosgruber** [comment]
@remh I think I did it and I was also wondering why it failed always on zookeeper and network test.

**Comment by irabinovitch** [comment]
@urosgruber The ZK tests were due to  a problem fixed in #2154. I believe these should pass once you rebase on master.

**Comment by urosgruber** [comment]
@irabinovitch rebased and now some timeout issues on 2 other tests.

**Comment by olivielpeau** [comment]
Looks good, thanks @urosgruber!

Merging.

**Pull request merged**
