### PR TITLE
[network] Use `ss` instead of `netstat` on linux

### PR DESCRIPTION
**Pull request by olivielpeau**
`netstat` is deprecated on many distributions, `ss` is its replacement and is present by default in the `PATH` on most of the distributions that I've tested (CentOS >= 6, Ubuntu >= 12.04, but not on CentOS 5).

We still fallback to `netstat` if `ss` is not installed.

Addresses https://github.com/DataDog/dd-agent/issues/1156

I've also checked that `subprocess.Popen` doesn't hang with `stdout=PIPE`: as long as we use it with `communicate()` (which we do here) we should be fine.

### CODE REVIEW

**Comment by remh** [comment]
Nice. Can you write a test that checks that the metrics collected are equivalent ?

**Comment by remh** [comment]
Also can you switch to this helper ? https://github.com/DataDog/dd-agent/blob/master/utils/subprocess_output.py

It will be easier to debug and is safer to use

**Comment by hkaj** [comment]
LGTM

**Comment by olivielpeau** [comment]
Thanks @hkaj and @remh for your reviews, merging.

**Pull request merged**
