### PR TITLE
Add check for fluentd

### PR DESCRIPTION
**Pull request by LeoCavaille**
[leo@datadoghq.com] rebased for new CI skeleton and no sudo use
Squashed a bunch of commits too

Rebased changes and work from @takus to work with the new CI (doesn't allow sudo any more), we install fluentd with `gem` easily instead. Replaces #1080.

Improved a little bit the test which did not fail if it received no metrics (because iterating on the set of metrics), so now the test expects a certain number of metrics and service checks to be output.

### CODE REVIEW

**Comment by LeoCavaille** [comment]
Thanks @takus again, merging your code for 5.2 !

**Comment by takus** [comment]
Thank you very much!!!!

**Comment by kzk** [comment]
:+1:

**Comment by yyuu** [comment]
:+1:

**Comment by jhotta** [comment]
wao!! ;)

**Pull request merged**
