### PR TITLE
[core] do not log API keys

### PR DESCRIPTION
**Pull request by yannmh**
Create a `utils.logger` module:
* Move `log_exceptions` from `utils.debug`
* `NoAPIKeyLogRecord` is a custom `LogRecord` that obfuscates API keys
  logging

### CODE REVIEW

**Comment by yannmh** [comment]
## Benchmarking

### Approaches
Available approaches are:

1. No processing, i.e API key is diplayed
2. Decorator hack to obfuscate (c.f. https://github.com/DataDog/dd-agent/pull/2144)
3. Custom `logging` LogRecord (exposed in this PR)
4. ~~Custom `logging` Filter.~~ Not a valid approach (used to exclude log lines or add extra logging information)

### Script
Available here: https://gist.github.com/yannmh/515f8560e0a3d1ca91c9

### Results

```
-> % python logging_benchmark.py
No processing: 0.028247
Decorator hack: 0.069303
Custom LogRecord: 0.044454
```

:trophy: Custom LogRecord :trophy: 

cc @talwai @remh

**Comment by remh** [comment]
@yannmh i don't understand why is the filter not a good fit?

something like
```
class ApiKeyLoggingFilter(logging.Filter):

    def filter(self, record):
        record.msg = record.msg.replace(apikey, "REDACTED")
        return True
```

should work i think

**Comment by yannmh** [comment]
@remh,
In this case `record.msg` returns the log message template, i.e `u"Sending %s to endpoint %s at %s"`. While `record.getMessage()` would return the formatted message,  there is no setter to change it. 

So to obfuscate the API key, there would be two options

1. Iterate over the `record` parameters to obfuscate API keys if found. It's slow and not elegant (same approach was done in the decorator approch)
2. Override `record.getMessage()` method, which is what is done with the custom `LogRecord ` approach.

**Comment by talwai** [comment]
:+1: to using `LogRecord` - I like this approach. Couple of things:
1. Can we add a quick test for the overridden `getMessage` function?
2. I think `RedactedLogRecord` might be a nicer name, but that's just an opinion :)

Looks good otherwise

**Comment by yannmh** [comment]
Thanks for you reviews @talwai, @remh 
 
1. Done :white_check_mark:
2. I agree. I switched the name to `RedactedLogRecord ` :lipstick:

**Comment by remh** [comment]
:+1:

**Pull request merged**
