### PR TITLE
[mongo] make timeout configurable and increase the default

### PR DESCRIPTION
**Pull request by benmccann**
We have one MongoDB instance that's misbehaving. It's a bit slow to connect to it because of the problems it's having and so it's difficult to tell what's wrong because we're not getting any metrics from it.

### CODE REVIEW

**Comment by benmccann** [comment]
@remh @yannmh could we tag this as the 5.5.0 release as well? thanks!

**Comment by yannmh** [comment]
Thanks for contributing @benmccann !

Yes, let's assess this change for the 5.5.0 agent release. Out of curiosity, do you know long the check takes to connect to your instance ?

**Comment by benmccann** [comment]
Normally it connects very quickly. But it looks like every so often there's some job that's just pounding our instance with unoptimized queries, and so when that happens we're seeing it take about 15s.

**Comment by remh** [comment]
Can we make it configurable instead ?

**Comment by benmccann** [comment]
Making it configurable sounds reasonable. I'd still like to increase the default since I think it's lower than it needs to be.

Do you have an example of how we'd make it configurable? E.g. is there a certain file we'd edit to set the config value? And then would we read it from init_config or agentConfig?

**Comment by remh** [comment]
etcd is a good example.
https://github.com/DataDog/dd-agent/blob/5.4.3/conf.d/etcd.yaml.example#L7
https://github.com/DataDog/dd-agent/blob/5.4.3/checks.d/etcd.py#L74

I agree that we can increase the default timeout as well, although 60secs seems a bit excessive.

Does 20 secs seem reasonable ?

Thanks again for the feedback and the PR!

**Comment by benmccann** [comment]
Would there be any problems caused by having the timeout be too high? Seems like it doesn't cost us much to make it higher.

I'd settle for 30 secs ;-)  We were taking about 15 secs to connect, which is dangerously close to 20 secs.

**Comment by benmccann** [comment]
I've updated this PR to have a configurable timeout with a default of 30s

**Comment by remh** [comment]
Having a connection hanging for too long can triggers the watchdog that would kill and restart the agent.
Basically the watchdog kicks off if the overall check loop takes more than 2minutes. 

So we are still fine with 30 secs but it's something we have to be cautious with :)

Thanks again for this!

**Comment by benmccann** [comment]
The only test that failed on Travis (`TRAVIS_FLAVOR=network`) also fails on master without this change

**Comment by yannmh** [comment]
Thanks a lot @benmccann, looks like all tests are passing now :tada:.

Since we can now set this `timeout` parameter from the YAML configuration file, I think it would make sense to switch back the default value to 10 seconds, so that collector doesn't hang for too long when the instance is unreachable. 

Also, we recently introduced some contribution [guidelines](https://github.com/DataDog/dd-agent/blob/master/CONTRIBUTING.md) to keep a nice, homogeneous, and easy to browse git history.
Would you mind rewording the commit title following these [rules](https://github.com/DataDog/dd-agent/blob/master/CONTRIBUTING.md#commits-titles) please ? Again, thank you for your contribution.

**Comment by benmccann** [comment]
Thanks @yannmh. I rebased to get the fix for the network tests and updated the commit message.

Regarding the `timeout`, I'm not sure 10s is a good default since we regularly go over that and I wouldn't be surprised if others hit the same issue. I understand we want to stay clear of the 2 min mark that @remh mentioned, but he seemed fine with 30s. Are there other issues? Does it hang the collection of your other metrics as well?

**Comment by benmccann** [comment]
Btw, @yannmh @remh I'll let you guys decide the default timeout issue and update the PR accordingly. I do think that 10s is rather low though and setting it to at least 20 would solve most of the problems we've seen. It's not clear to me what negative effects there might be from setting it higher

**Comment by benmccann** [comment]
Yep, all tests are passing now! Thanks guys!

**Comment by yannmh** [comment]
Thanks for the further explanations @benmccann. Let's keep it at 30s then.

Merging :rocket: !

**Pull request merged**
