### PR TITLE
[core] Move to versioned endpoints for the agent

### PR DESCRIPTION
**Pull request by remh**
Also add headers about the version of the agent and of the forwarder

Note that this test will fail until the new endpoints are created and properly configured.

### CODE REVIEW

**Comment by remh** [comment]
cc: @miketheman @alq666 @LeoCavaille

**Comment by LeoCavaille** [comment]
Looks fine to me, I wonder if the `-app` is actually useful giving that we already namespace by the `.agent` subdomain.

**Comment by remh** [comment]
This is to allow new endpoints like:

5.2.0-metrics.agent.datadoghq.com
5.2.0-metadata.agent.datadoghq.com 

in the future.

**Comment by LeoCavaille** [comment]
Interesting! How about we create the endpoint before merging it so we can verify your test actually works.

**Comment by remh** [comment]
yup @miketheman is on it

**Comment by remh** [comment]
New ELBs are in place. Merging!

**Pull request merged**
