### PR TITLE
[HTTP/TCP Check] Add support for custom tags 

### PR DESCRIPTION
**Pull request by remh**
And get rid of legacy ch…eck names

The old check names are currently transformed in the backend

cc: @conorbranagan

### CODE REVIEW

**Comment by conorbranagan** [comment]
lgtm :+1:

**Comment by LeoCavaille** [comment]
@remh some tests in the CI are failing, could you have a look and try to run these tests locally?

**Comment by remh** [comment]
Yeah looks like there are more tests impacted by this change than the http check test, fixing it.

**Comment by remh** [comment]
Build is passing, merging.

**Comment by VynceMontgomery** [comment]
any progress here?

**Comment by remh** [comment]
@VynceMontgomery this was released with Agent 5.4.0 https://github.com/DataDog/dd-agent/blob/master/CHANGELOG.md#540--06-16-2015

**Pull request merged**
