### PR TITLE
[network] Support netstat in Windows

### PR DESCRIPTION
**Pull request by masci**
Original code from #2352 

Rebased on master + minor fixes

### CODE REVIEW

**Comment by olivielpeau** [comment]
Tested on windows 2012, looks good to me!

@masci Could you squash all the commits into one (and preserve the authorship)? Thanks!

**Comment by olivielpeau** [comment]
Actually it'd be good to add a comment in `network.yaml.default` to specify that on Windows an instance needs to be there for the check to run but that its configuration is ignored.

**Comment by olivielpeau** [comment]
Discussed with @remh about this addition and he was thinking about implementing this with `psutil` (`psutil.net_connections()`) instead of parsing `netstat`'s output.

**Comment by masci** [comment]
Superseded by #2499

**Pull request closed without merging**
