### PR TITLE
Add check for fluentd

### PR DESCRIPTION
**Pull request by takus**
Add AgentCheck for [Fluentd](http://www.fluentd.org/). This check enables us to create a dashboard like this:

fluentd___datadog

### CODE REVIEW

**Comment by kiyoto** [comment]
What's the latest on this? I am setting up agent_check for Fluentd (and potentially contributing an article to datadog's blog) and would love to see this merged upstream =)

**Comment by takus** [comment]
@kiyoto 
I'll finish to implement a feature to tag metrics by fluentd's `plugin-id` during this week. Sorry for waiting you.

**Comment by takus** [comment]
@LeoCavaille @kiyoto 
I finished to implement this PR. Now, this integration captures metrics of plugins that has specified plugin_id in `plugin_ids` parameter. I think it's useful for set different monitoring threshold for each output plugin type.

fluentd___datadog

**Comment by LeoCavaille** [comment]
Closing, merged in #1301 with additional modifications. Thanks.

**Pull request closed without merging**
