### PR TITLE
[mysql] Innodb status metrics (Percona)

### LINKED ISSUE #152: (Much) better mysql metrics
Pre-baked from http://www.percona.com/doc/percona-monitoring-plugins/cacti/mysql-templates.html

@conorbranagan came up during a conversation with a customer today. There's plenty of work to do on the collection side, but for rev2 of the mysql prebaked dash, this is an excellent source.

### PR DESCRIPTION
**Pull request by garnermccloud**
Parse Innodb Status to get Percona Style metrics

Cleaned up, rebased and added testing to #1269

Fixes #152 and #685

### CODE REVIEW

**Comment by remh** [comment]
@ovaistariq I'm going to assign a new reviewer to work on this one and expect to release it with our 5.7.0 release. In the meantime you can use this check as a custom check.

**Comment by ovaistariq** [comment]
@remh thanks for the update. I am already using it as a custom check. But would love to see it released soon as a standard check.

**Comment by ovaistariq** [comment]
@remh Would this be released with a Datadog agent release before April 2016? I was hoping to do a talk around Datadog monitoring for MySQL at Percona Conference in 2016 (which is the biggest annual MySQL conference).

**Comment by irabinovitch** [comment]
@ovaistariq We expect a few agent releases before then.  If you drop me a line via email ilan@datadoghq.com we'd be happy to collaborate or support you regarding the session.

**Comment by irabinovitch** [comment]
FYI the new test failures look to be flake8 related.

./checks.d/mongo.py:476:25: F821 undefined name 'types'
./checks.d/mongo.py:476:40: F821 undefined name 'types'
./checks.d/mongo.py:476:56: F821 undefined name 'types'
./checks.d/mongo.py:484:1: W391 blank line at end of file

**Comment by ovaistariq** [comment]
@irabinovitch I have sent you an email, thanks.

**Comment by MiguelMoll** [comment]
There are some really neat metrics being collected that we would love to take advantage of. Thought I'd bump this convo and maybe get an ETA? Thanks!

**Comment by irabinovitch** [comment]
@MiguelMoll We are working towards inclusion in our 5.7 agent release which is the next major release.

**Comment by irabinovitch** [comment]
@truthbk  @garnermccloud  can we close this in favor of #2116 which is slated for 5.7?

**Comment by irabinovitch** [comment]
Closing this. We'll track further in #2116 which is a refactored version of this pr and a few others.

**Pull request closed without merging**
