### PR TITLE
Support tags for process check

### PR DESCRIPTION
**Pull request by amalakar**

### CODE REVIEW

**Comment by remh** [comment]
Thanks a bunch a @amalakar  !

Our master branch is currently frozen for the preparation of our 5.2.0 release.

We'll review your pull request for our 5.3.0 release.
Thanks again!

**Comment by remh** [comment]
Thanks for this @amalakar .
Could you try to copy an example of how we implement custom tags usually ?
Here is an example:
https://github.com/DataDog/dd-agent/blob/master/conf.d/redisdb.yaml.example#L17-L21

Also could you add tests to make sure that this functionality doesn't get broken in the future :)

Thanks again!

**Comment by LeoCavaille** [comment]
Thanks @amalakar again for contributing, I opened a new PR (see above) rebasing your changes and adding some more testing stuff on top of it. Will merge that one instead. Closing.

**Comment by amalakar** [comment]
@LeoCavaille thank you!

**Pull request closed without merging**
