### PR TITLE
Mysql Handler Statistics for Index Usage

### PR DESCRIPTION
**Pull request by polynomial**
These statistics improve visibility into index performance
and usage. Documentation for the stats:
http://dev.mysql.com/doc/refman/5.7/en/server-status-variables.html#statvar_Handler_commit

### CODE REVIEW

**Comment by remh** [comment]
Thanks a lot @polynomial we will review this for our 5.7.0 release.

**Comment by irabinovitch** [comment]
@remh  @polynomial  I believe these maybe a subset of #2027 which is scheduled for 5.7.0 as well.  Thoughts on closing and following there?

**Comment by polynomial** [comment]
1869 is missing Handler_prepare, otherwise that would be awesome.

**Comment by irabinovitch** [comment]
@truthbk Can we get Handler_prepare added in #2116 ?

CC: @ovaistariq

**Comment by ovaistariq** [comment]
@irabinovitch I think we should ad Handler_prepare to #2116 together with the other Handler_* metrics as "Additional (and optional) Status Metrics".

**Comment by truthbk** [comment]
@polynomial @ovaistariq @irabinovitch these have now been added to #2116, including `Handler_prepare` which was missing. Thanks @polynomial!

**Comment by irabinovitch** [comment]
@truthbk Thanks!

@polynomial  I'm going to close this in favor of #2116. Thanks for raising it!

**Pull request closed without merging**
