### PR TITLE
[dependencies] Upgrade boto 2.36.0 -> 2.39.0

### PR DESCRIPTION
**Pull request by JohnLZeller**
There is a bug in boto 2.36.0 that is fixed in the 2.39.0 release: https://github.com/boto/boto/pull/3399

### CODE REVIEW

**Comment by JohnLZeller** [comment]
@olivielpeau where else does this need to be updated, if any?

**Comment by olivielpeau** [comment]
@JohnLZeller You'll have to update it here too: https://github.com/DataDog/omnibus-software/blob/5.7.3/config/software/boto.rb#L2

Have you been able to test that the upgrade doesn't break anything? (I see the module getting imported there: https://github.com/DataDog/dd-agent/blob/5.7.3/util.py#L385 and there: https://github.com/DataDog/dd-agent/blob/5.7.3/checks.d/riakcs.py#L5)

**Comment by JohnLZeller** [comment]
Here it is in omnibus, and I shall test that now :)

https://github.com/DataDog/omnibus-software/pull/46

**Comment by JohnLZeller** [comment]
Looks like this is gonna work fine :)

**Pull request merged**
