### PR TITLE
Redis and ps check for mperham/sidekiq

### PR DESCRIPTION
**Pull request by donaldguy**
Monitors sidekiq via its (namespaced) redis keys per the schema
used in http://git.io/e-QGLw (lib/sidekiq/api.rb)

Per @mperham in #1150, this schema is stable.

Also does a service check on the existence and non-terminated state
of worker processes with a given tag.

Supersedes, and thereby closes #1150 

---
I would suggest there might still be an interesting pattern generally in that PR - but this one is more practical

### CODE REVIEW

**Comment by irabinovitch** [comment]
@donaldguy Thank you for your contribution.  We were hoping to check back in and see if you had any luck getting tests to pass and/or addressing some of the code review comments from  Leo. Thank you for being a part of the Datadog community.

**Comment by skwp** [comment]
Really want this!

**Comment by irabinovitch** [comment]
@skwp Thanks for your note and feedback on the PR. We would love to include this in a future release of the agent.  Would you be interested in continuing the work @donaldguy  started on this pull request? It looks like we are mostly there, but need to address a few of the comments from @LeoCavaille and get tests working before we can merge.

**Comment by donaldguy** [comment]
Yeah, I changed jobs and am no longer working with sidekiq or datadog, so I don't know when I would get around to this :( 

anyone who wants to pick it up feel more than free

**Comment by irabinovitch** [comment]
@donaldguy Thanks for the quick reply here! Appreciate your efforts on the initial PR.  We hope to have a chance to work with you again in the future.  Happy monitoring!

**Comment by LeoCavaille** [comment]
@irabinovitch I've came across https://github.com/bsm/sidekiq-datadog on twitter. Not tested, but I think adding a middleware would be another way of getting metrics for sidekiq, not sure which is better (usually the active, aka. middleware is better because it's easier to get contextual info).

**Comment by poblahblahblah** [comment]
We have a decent sidekiq footprint and what we've decided on doing is pulling out the sidekiq stats we need directly from redis. Sidekiq already supports statsd out of the box, so we were able to pull a bunch of data from there but what we were missing, and what we really needed, was to alert on when queues get backed up. Here's a sample config for a default sidekiq queue using the redisdb check:

```
init_config:

instances:
  - host: localhost
    port: 6379
    keys:
      - sidekiq:queue:highpriority
      - sidekiq:queue:lowpriority
      - sidekiq:queue:default
      - otherservice-sidekiq:queue:highpriority
      - otherservice-sidekiq:queue:lowpriority
      - otherservice-sidekiq:queue:default
```

We regularly get large dumps of jobs into the default queue so alerting on that is not ideal, but our `highpriority` queue should *never* back up. If it is more than 1 on average for 5 minutes then we know something is wrong so that's what we alert on.

AFAIK sidekiq will default namespace the sidekiq queue to "sidekiq", but this can be overwritten. You can get the list of sidekiq instances and queues directly from each redis instance. I used ruby and the redis gem to do this:

```
# connect
require 'redis'
redis = Redis.new

# get all sidekiq queues:
redis.keys("*:queues")
 => [ "sidekiq:queues", "otherservice-sidekiq:queues", "thirdservice-sidekiq:queues" ]

# get sub queues
redis.smembers('sidekiq:queues')
 => ["highpriority", "lowpriority", "default"]

# get queue count:
redis.llen('sidekiq:queue:highpriority')
 => 12
```

Hopefully this is helpful to others.

**Comment by irabinovitch** [comment]
@poblahblahblah As a sidekick user would you see value in a dedicated SideKick integration, or do you feel the redisdb check along with some sidekick specific documentation would be sufficient?

**Comment by poblahblahblah** [comment]
@irabinovitch yes, I would see value in a dedicated integration. Sidekiq has a pretty large install base in the ruby world. I've been meaning to dig into this PR to see if I can update it per suggestions, but my python is really rusty.

**Comment by poblahblahblah** [comment]
@irabinovitch I spent a bit of time this morning fixing the branch up a bit. I don't think I can take over this PR, though.

branch: https://github.com/poblahblahblah/dd-agent/tree/redis-sidekiq-check
commit: https://github.com/poblahblahblah/dd-agent/commit/99f6967749d299aad1f142b8dfc848d1d50dfee4

**Comment by bmarini** [comment]
I've created a separate PR for sidekiq that is only concerned with pulling information out of sidekiq keys from a redis connection: #2066 It has tests, and is also designed to work with the sidekiq-pro reliable fetch feature.

**Comment by poblahblahblah** [comment]
#2066 looks good to me.

**Comment by irabinovitch** [comment]
Thanks all. Appreciate the follow through on this one! I'm going to close this ticket in favor of #2066

**Comment by collimarco** [comment]
@poblahblahblah I can't find the right names for the keys... I don't use any namespace and I can find the set `queues` with all the queue names. However I keep getting:

```
    redisdb (5.17.2)
    ----------------
      - instance #0 [WARNING]
          Warning: queue:deliveries key not found in redis
          Warning: queue:default key not found in redis
          Warning: queue:low key not found in redis
```

Any idea about what keys I should try?

**Pull request closed without merging**
