### PR TITLE
added pm2 (for Node.js) check

### PR DESCRIPTION
**Pull request by bkarakashev**
I was looking all over for such a check for Datadog but couldn't find. So I have decided to make one myself. Basically, this is Datadog check for PM2.

### CODE REVIEW

**Comment by irabinovitch** [comment]
@bkarakashev  Thank you for your contribution and for being part of the Datadog community. On initial review it appears some of the tests may be failing after this change. Would you mind taking a look and addressing? 

Some of them appear to be style related, but there may be other failures as well.
./checks.d/pm2.py:4:1: F401 'time' imported but unused
./checks.d/pm2.py:42:1: W391 blank line at end of file

We look forward to merging this in an upcoming release.

-Ilan

**Comment by irabinovitch** [comment]
@bkarakashev Were you able to take a look at the flake8 failures? The merge window for the Datadog 5.7 release is closing shortly.

**Comment by irabinovitch** [comment]
@bkarakashev Just checking back in regarding the test failures. We'd like to include your improvements once these have been addressed.

**Comment by swordfish444** [comment]
@irabinovitch Is there any update on support for pm2? I'm finding it quite difficult to get monitoring setup for each of the pm2 processes.

**Comment by gmmeyer** [comment]
Hi @bkarakashev,

Thanks again for your contribution, always very much appreciated. 

We're currently transitioning our checks to a new SDK-based model for the agent. An unfortunate side-effect is that we have to impose a freeze on the dd-agent repo. 

The SDK consists of two repositories https://github.com/DataDog/integrations-core and https://github.com/DataDog/integrations-extras, where all of our checks will reside. This PR would belong in the extras repository. Would you be so kind as to re-open the PR there? 

We have facilitated some tools to help you with the SDK development that should help you get up and running in no time: [sdk guide](http://docs.datadoghq.com/guides/integration_sdk/) [datadog sdk gem]( https://github.com/DataDog/datadog-sdk-testing). We are very sorry for the inconvenience caused. 

Thank you for your patience as we make this transition!

**Comment by gmmeyer** [comment]
We're going to keep this open for now, we'll port this over on a branch to the [integration extras](https://github.com/DataDog/integrations-extras) repo. You can take it from there once that work has completed and we can close this then.

**Comment by sheltonial** [comment]
Hi @gmmeyer, if there is a new home for this issue in `integration extras` (or elsewhere) could you please provide a link. Otherwise, how can I help contributing to get this feature in DataDog?

**Comment by gmmeyer** [comment]
Hey @sheltonial! 

Glad you're willing to help! I don't see it over there, so it appears we missed this one. I can help you port it over there if you want. Basically, it needs to be moved over there, some tests will need to be written for it and that's about it. If you'd like help, we'll be happy to provide some help!

If you want it in integrations-extras, the biggest thing you can do is to become the official maintainer  of the check. Extras are community checks, which means that they're not officially supported by Datadog, but supported by members of the community.

Let us know if you need any help!

-Greg

**Comment by irabinovitch** [comment]
Closing this in favor of integrations-extras/pull/89

**Pull request closed without merging**
