### PR TITLE
[utils] Use TemporaryFile default 'w+b', not 'rw'

### PR DESCRIPTION
**Pull request by JohnLZeller**

### CODE REVIEW

**Comment by JohnLZeller** [comment]
@olivielpeau r?

**Comment by olivielpeau** [comment]
:+1:

**Comment by JohnLZeller** [comment]
@olivielpeau r? again :)

**Comment by olivielpeau** [comment]
Carefully reviewed while re-reading the python docs, this looks ready to :ship:!

**Pull request merged**
