### PR TITLE
[memory_snapshot] First pass

### PR DESCRIPTION
**Pull request by remh**
This is a quick check that will send an event with the list of processes that have the highest memory footprint (rss) when the overall memory usage is higher than X percent

It's not ready to be merged yet but it's here for discussion.

Still need to add a test, docs, and get some feedback and get a better rendering.

E.g. of event it's creating:

image

### CODE REVIEW

**Comment by remh** [comment]
Not sure we want to merge that yet, as we should rework the process tree instead but it's here for discussion and for version control.

**Comment by remh** [comment]
Another example https://app.datadoghq.com/event/event?id=2818088290886882367

**Comment by VynceMontgomery** [comment]
on IRC it came up that this functionality, or something like it, but for CPU would also be very nice to have.

**Comment by gmmeyer** [comment]
Closing in the integration sdk cleanup.

**Pull request closed without merging**
