### PR TITLE
[http_check] no_proxy changed default True and Silent ssl warning

### PR DESCRIPTION
**Pull request by n0ts**
Hi, all.
I fix a http_check silent InsecureRequestWarning.
And no_proxy default change False to True.
I think that normally no use proxy.
https://github.com/DataDog/dd-agent/commit/4f7d3821efdd154fd0cbf1e7de7eb2cdab81ee3f

Could you review it?

### CODE REVIEW

**Comment by truthbk** [comment]
@n0ts thank you for this contribution as well! We'll review it shortly, but this definitely makes sense as well! 😄

**Comment by n0ts** [comment]
@truthbk Hi, I rebased branch on master.

**Comment by n0ts** [comment]
@truthbk What is the PR status?

**Comment by degemer** [comment]
Hello @n0ts, sorry for the late response.

 You can set `PYTHONWARNINGS="ignore:Unverified HTTPS request"` environment variable in `supervisor.conf`: replace this line https://github.com/DataDog/dd-agent/blob/563f632dfc9f50ef6e2e230c5d88c2dabe4817f1/packaging/supervisor.conf#L31 by `environment=PYTHONPATH='/opt/datadog-agent/agent:/opt/datadog-agent/agent/checks/libs:$PYTHONPATH',PYTHONWARNINGS="ignore:Unverified HTTPS request"`, and those errors should disappear.

I'm going to close this PR, please let me know if it works for you or if you think we should include this change!

**Pull request closed without merging**
