### PR TITLE
[mysql] Fixes #152. Enhancing current set of metrics captured

### LINKED ISSUE #152: (Much) better mysql metrics
Pre-baked from http://www.percona.com/doc/percona-monitoring-plugins/cacti/mysql-templates.html

@conorbranagan came up during a conversation with a customer today. There's plenty of work to do on the collection side, but for rev2 of the mysql prebaked dash, this is an excellent source.

### PR DESCRIPTION
**Pull request by ovaistariq**
Enhancing current set of metrics captured by mysql check. The current set of MySQL metrics provided by Datadog is very limited (based on my experience as a Senior MySQL Consultant at Percona).

The following changes have been made to the mysql check:
a. Its heavily inspired by MySQL cacti template provided by Percona
which contains an extensive set of checks that are important to measure
the performance and health of a MySQL server. For reference please look
at this URL:
http://www.percona.com/doc/percona-monitoring-plugins/1.1/cacti/mysql-templates.html#sample-graphs

b. Many of the important metrics exposed by Percona Server / MariaDB Server are
not available in MySQL Server as status variables, these have been added
by parsing the output of "SHOW ENGINE INNODB STATUS"

### CODE REVIEW

**Comment by ovaistariq** [comment]
Not sure why the latest Travis build failed. It seems to be unrelated to my commit.

**Comment by remh** [comment]
Thanks  a lot @ovaistariq our set of new features is frozen for our 5.2.0 release.

We'll review for our 5.3. release.
Thanks again!

**Comment by ovaistariq** [comment]
Thanks Remi. I still need to see why Travis build is failing though I have this running fine on a couple of hundred of servers :)

**Comment by irabinovitch** [comment]
Hi @ovaistariq,  First I wanted to thank you for all of your MySQL related contributions, and apologize for the delay in getting back to you. We're excited about all the new metrics this will make available and are currently tracking this for an upcoming release.

To give you an update, since the code base has diverged a bit since your PR in January, @garnermccloud  has rebased your commits in #1869, as well as added a few test cases to our integration test suite.  

If you're ok with it, we'd like to close #1269 out and track the remaining testing work over in #1869.  If you have a moment we'd be happy to have your review/feedback on his changes there.

Thank you for your efforts to improving the MySQL integration, and for being part of the Datadog community.

Regards,
Ilan

**Comment by garnermccloud** [comment]
Closing this PR as I've rebased it in https://github.com/DataDog/dd-agent/pull/1869 . Thanks again @ovaistariq for your contributions!

**Comment by ovaistariq** [comment]
@irabinovitch I have taken a brief look at #1869 and it looks good. I agree that this one can be closed.

**Pull request closed without merging**
