### PR TITLE
[kafka] bumping kafka-python package version to 1.2.5.

### PR DESCRIPTION
**Pull request by truthbk**
*Note: Please remember to review the Datadog [Contribution Guidelines](https://github.com/DataDog/dd-agent/blob/master/CONTRIBUTING.md)
if you have not yet done so.*

### What does this PR do?

Bumps the version of the kafka-python package.

### Motivation

Improve support for newer kafka's.

### Testing Guidelines

An overview on [testing](https://github.com/DataDog/dd-agent/blob/master/tests/README.md)
is available in our contribution guidelines.

### Additional Notes

(none)

### CODE REVIEW

**Comment by truthbk** [comment]
There will be a race condition when deploying between the agent's lib, and the custom check getting updated to use the new lib.

**Comment by olivielpeau** [comment]
Looks good to me, let's merge this along with its omnibus-software counterpart, build a custom package and deploy it on staging as we would do on prod

**Comment by truthbk** [comment]
omnibus-software PR: https://github.com/DataDog/omnibus-software/pull/70

**Comment by truthbk** [comment]
CI failures were unrelated to changes.

**Pull request merged**
