### PR TITLE
Aerospike Integration

### PR DESCRIPTION
**Pull request by AniruddhaSAtre**
Publishing Aerospike Integration Service for Datadog. Aerospike is the World's First Flash-optimized,
In-memory, NoSQL Database.

### CODE REVIEW

**Comment by yannmh** [comment]
Hey @AniruddhaAtre-GSLab, thanks a lot for taking the time to write an entire new check :smiley:

We'll review it, and are looking forward to including it in a future version of the agent.

Thanks again!

**Comment by remh** [comment]
Thanks a lot @AniruddhaAtre-GSLab 
Any reason you didn't use the existing Aerospike python client ? https://github.com/aerospike/aerospike-client-python

**Comment by AniruddhaAtre-GSLab** [comment]
Hi,

Aerospike python client spits out lot of information and only in one
particular format. We need to do a few calculations and parsing in order to
send these metrics into Datadog system. So we didn't use Aerospike python
client.

We were in touch with Will Xu from Datadog earlier. We were told that one
blog post will be created for Aerospike plugin and sent for review. Also
review of this plugin will be communicated. But we have not heard anything
from him for a long time now even after repeated requests. Could you please
update us on this ? Also we would like to know schedule of release.

Thanks.

Regards,

Aniruddha

**Comment by AniruddhaAtre-GSLab** [comment]
I have incorporated all the changes suggested by Datadog team and informed by Will Xu. Now this Aerospike Datadog connector is ready to publish.

**Comment by joshk0** [comment]
Hello, are there still plans to integrate this connector into the upstream Agent? If necessary, I could adopt this PR and deal with any other issues that are presented.

**Comment by joshk0** [comment]
Looks superseded by #1775.

**Comment by irabinovitch** [comment]
@AniruddhaSAtre  Can we close this in favor of #1775 ?

**Comment by irabinovitch** [comment]
Closing in favor of #1775

**Pull request closed without merging**
