### PR TITLE
SSH check on Windows (beta)

### PR DESCRIPTION
**Pull request by truthbk**
Note, this will *not* be merged into master - at least not immediately.

### CODE REVIEW

**Comment by irabinovitch** [comment]
Reran tests. They're passing now.

**Comment by remh** [comment]
@truthbk can you fix the commit please ?

**Comment by remh** [comment]
@truthbk ping on this one

**Comment by truthbk** [comment]
@remh fixed the commit! Sorry for the delay.

**Comment by truthbk** [comment]
Fixed up conflicts.

**Comment by remh** [comment]
Let's remember to check the final build for that.

**Pull request merged**
