### PR TITLE
[hdfs] Deprecate previous hdfs check

### PR DESCRIPTION
**Pull request by olivielpeau**
- add a deprecation notice on the old check
- add to the new check a metric (`capacity_in_use`) that was sent by the old check

### CODE REVIEW

**Comment by remh** [comment]
You could also add a `self.warning` similar to https://github.com/DataDog/dd-agent/blob/master/checks.d/docker.py#L134-L135

**Comment by olivielpeau** [comment]
Makes sense, thanks, I've added the warning.

**Comment by olivielpeau** [comment]
CI failures are unrelated, merging.

**Comment by irabinovitch** [comment]
Do we have a ticket to track the spurious CI failures?

**Comment by olivielpeau** [comment]
@irabinovitch No, but I agree that it'd be good to have one, thanks. Could you create one?

**Pull request merged**
