### PR TITLE
[dropwizard] Add a Check for the popular Java Dropwizard framework

### PR DESCRIPTION
**Pull request by cberry777**
### What does this PR do?

Adds a new DropwizardCheck.
A DataDog check for the popular Java Dropwizard framework.

### Motivation

Dropwizard is a widely popular Java framework for creating microservices.
(For further details, see http://metrics.dropwizard.io/3.1.0/)
The Java world really needs a first class check in DataDog for Dropwizard services.

DropwizardCheck calls the standard Dropwizard stats URL: http://localhost:8081/metrics -- which yields up a JSON response consisting of the all metrics in it's MetricRegistry at that time. DropwizardCheck reads this response, parses it, and creates the corresponding DataDog metrics.

### Testing Guidelines

A Testcase is provided here: tests/checks/mock/test_dropwizard.py
It contains 5 tests.

### Additional Notes

Please see the DropwizardCheck (checks.d/dropwizard.py) for quite a bit of documentation.

NOTE: A form of this code has been running in Production for many months at my employer.
And we've decided to make it available to all...

### CODE REVIEW

**Comment by cberry777** [comment]
This is failing because of a flaky test -- as far as I can tell

**Comment by cberry777** [comment]
@masci - any idea if this PR will get considered?
THANKS

**Comment by masci** [comment]
Hi @cberry777 ,
we're moving our checks in a separate repo to ease the release process. This check is definitely going to be merged there, we're still finalising the details but I'll be back to you as soon as we're ready to merge, hopefully with the next Agent release.

**Comment by cberry777** [comment]
@masci -- thanks very much.
This is definitely a missing check for the Java world... So that's Great!
That is a good idea to split the repos.
I do hope that the additional_checks bit won't change -- that is how we do our integration w/ y'all

I have another Check y'all need -- for Jolokia based metrics
But I'll wait until the split...

Thanks again!

**Comment by masci** [comment]
Hi @cberry777,

Thanks again for your contribution, always very much appreciated. We're currently transitioning our checks to a new SDK-based model for the agent. An unfortunate side-effect is that we have to impose a freeze on the dd-agent repo. The SDK consists of two repositories https://github.com/DataDog/integrations-core and https://github.com/DataDog/integrations-extras, where all of our checks will reside. This PR would belong in the core/extras repository. Would you be so kind as to re-open the PR there? We have facilitated some tools to help you with the SDK development that should help you get up and running in no time: [sdk guide](http://docs.datadoghq.com/guides/integration_sdk/) [datadog sdk gem]( https://github.com/DataDog/datadog-sdk-testing). We are very sorry for the inconvenience caused. 

Thank you for your patience as we make this transition!

**Comment by truthbk** [comment]
@cberry777, @masci and I, we've taken the liberty of opening a PR here to help you transition to the SDK DataDog/integrations-extras#36

We created a patch with your work and dropped it that PR. Please feel free to continue your work there. 🙇

**Pull request closed without merging**
