### PR TITLE
[mysql] Adds new query cache metrics

### PR DESCRIPTION
**Pull request by leucos**
This commit adds 7 new query cache (QCache) metrics to the mysql
monitor:

- Qcache_free_blocks
- Qcache_free_memory
- Qcache_inserts
- Qcache_lowmem_prunes
- Qcache_not_cached
- Qcache_queries_in_cache
- Qcache_total_blocks

These metrics are very helpful tuning the query cache.

### CODE REVIEW

**Comment by irabinovitch** [comment]
@truthbk This looks to fit with your work on #2116. mind taking a look when you have a moment?

CC: @ovaistariq

**Comment by leucos** [comment]
Indeed, besides `Qcache_free_blocks` and `Qcache_total_blocks`, everything is covered in #2116. It is probably better to ditch this PR and add those status variables to #2116.

**Comment by ovaistariq** [comment]
@leucos #2116 provides ```mysql.performance.qcache_size``` and ```mysql.performance.qcache_free_memory``` metrics which provide the same data as ```Qcache_free_blocks``` and ```Qcache_total_blocks```. The difference being that the *_blocks metrics provide data using blocks as the measurement scale, while the ones provided by #2116 provide the data in bytes form. Hence *_blocks metrics would be redundant.

**Comment by leucos** [comment]
@ovaistariq indeed, but since query cache block size is not a fixed value, you can not deduce block count from mysql.qcache_size. And knowing free/total blocks count is really important to monitor query cache fragmentation.

**Comment by truthbk** [comment]
@ovaistariq @leucos @irabinovitch pending further discussion I have tentatively added the metric to #2116 - most was already covered anyways.

**Comment by irabinovitch** [comment]
@truthbk  thanks!

@leucos mind if we close this and track the remaining discussion in #2116?

**Comment by leucos** [comment]
Sure @irabinovitch !

**Pull request closed without merging**
