### PR TITLE
add activemq_xml agent check

### PR DESCRIPTION
**Pull request by brettlangdon**
I wrote a quick ActiveMQ agent check based on the xml queue status page, e.g. `http://user:pass@localhost:8161/admin/xml/queues.jsp`

It will emit the following gauges for each queue with the tag `queue:<queue-name>`
* `activemq.queue.consumer_count`
* `activemq.queue.dequeue_count`
* `activemq.queue.enqueue_count`
* `activemq.queue.size`

And an additional gauge `activemq.queues.count` which is the total count of queues.

### CODE REVIEW

**Comment by remh** [comment]
Thanks @brettlangdon !
It looks like your tests are failing on 
```python
======================================================================
ERROR: test_process_topics_data_normal (tests.test_activemq_xml.ActiveMQXMLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/DataDog/dd-agent/tests/test_activemq_xml.py", line 147, in test_process_topics_data_normal
    check._process_topic_data(data)
  File "/home/travis/build/DataDog/dd-agent/checks.d/activemq_xml.py", line 82, in _process_topic_data
    for topic in root.iter("topic"):
AttributeError: _ElementInterface instance has no attribute 'iter'
```

**Comment by brettlangdon** [comment]
:(

I'll take a look, thanks.

**Comment by brettlangdon** [comment]
@remh all good, `.iter` isn't supported in 2.6

**Comment by remh** [comment]
Thanks @brettlangdon !

**Pull request merged**
