### PR TITLE
Kong check

### PR DESCRIPTION
**Pull request by shashiranjan84**
[Kong](https://getkong.org/) is an API Gateway and Management solution. Check will send metrics
for the NGINX server in format kong.server.x and for the Database in following format kong.server.x

Examples: 
kong.server.connections_handled
kong.server.oauth2_tokens

### CODE REVIEW

**Comment by irabinovitch** [comment]
@shashiranjan84 Thank you for contributing the KONG integration.  Have you by any chance had an opportunity to review why the tests are failing?

**Comment by shashiranjan84** [comment]
@irabinovitch I need some help getting it through. I have had hard understanding your CI system. I am currently getting following error which i don't know why .

https://travis-ci.org/DataDog/dd-agent/jobs/89973489#L437

Hire i am trying to copy cassandra conf file

**Comment by shashiranjan84** [comment]
@irabinovitch can you help me here, My test are failing in Travis environment but same test works in my local if just my Application and run test as unit test locally 

https://travis-ci.org/DataDog/dd-agent/jobs/90422834#L597

screenshot 2015-11-10 17 02 57

Not sure what I am doing wrong.

**Comment by sinzone** [comment]
:+1:

**Comment by remh** [comment]
Thanks a lot @shashiranjan84 we'll review this for our 5.7.0 release.

**Comment by shashiranjan84** [comment]
Hey thanks, but I have to close this pull request as I have to update the code with new version. Will send another PR  once its ready.

**Comment by irabinovitch** [comment]
@shashiranjan84 Were you able to open a new PR?

**Comment by shashiranjan84** [comment]
We currently working on next release for our product which will have better
support  for DD agent. So once its i ll send a PR again.

**Pull request closed without merging**
