### PR TITLE
Custom MySQL Metrics

### PR DESCRIPTION
**Pull request by obi11235**
Allow users to create custom MySQL metrics for their applications using a query. By including it in the standard MySQL check it will reuse the connection the datadog agent is already making.

### CODE REVIEW

**Comment by remh** [comment]
Thanks @obi11235 ! Our 5.2.0 release is now frozen. So we'll aim at reviewing it for our 5.3 release.

Thans a lot!

**Comment by mansilladev** [comment]
+1 please merge. :)

**Comment by mboylevt** [comment]
+2!  Would love this in the next release.

**Comment by talwai** [comment]
Closing in favor of #1793

**Pull request closed without merging**
