### PR TITLE
support reporting of page fault stats

### PR DESCRIPTION
**Pull request by ovesh**
page fault stats are not supported in psutil.
This pull request reads the 4 relevant stats (minflt, cminflt, majflt, cmajflt) from `/proc/{pid}/stat`.

### CODE REVIEW

**Comment by olivielpeau** [comment]
Hi @ovesh, thanks for contributing! 

We'll review your PR in details soon, but I have a few comments after having a quick look at your changes:
- Could you have a look at the `flake8` failures listed [here](https://travis-ci.org/DataDog/dd-agent/jobs/105999552#L301-L303) and fix them?
- Could you make sure to stick to the [contribution guidelines](https://github.com/DataDog/dd-agent/blob/master/CONTRIBUTING.md#commits), in particular could you squash your commits into one and have a descriptive commit title?

Thanks again!

**Comment by irabinovitch** [comment]
@ovesh thanks again for your PR.  Were you able to take a look at the style failures?

**Comment by ovesh** [comment]
@irabinovitch, I have just been swamped with work. I'm going to get to this towards the end of March.

**Comment by ovesh** [comment]
moved to a squashed pull request in https://github.com/DataDog/dd-agent/pull/2363

**Pull request closed without merging**
