### PR TITLE
[rabbitmq] Added data collection for exchanges

### PR DESCRIPTION
**Pull request by wholroyd**
### What does this PR do?

This PR adds functionality to the RabbitMQ integration to collect metrics on exchanges in addition to data already collected for nodes and queues.

### Motivation

Inability to see what is going onto an Exchange and not necessarily into a queue.

### Testing Guidelines

An overview on [testing](https://github.com/DataDog/dd-agent/blob/master/tests/README.md)
is available in our contribution guidelines.

### Additional Notes

Think I did everything required, although the test coverage report doesn't say what isn't covered and PyCharm doesn't merge results of Mock and Integration tests.

### CODE REVIEW

**Comment by wholroyd** [comment]
Working on the issues Travis found in https://travis-ci.org/DataDog/dd-agent/jobs/176140375.

**Comment by wholroyd** [comment]
Seems like Travis is choking on the very first CI command to build up the queues and exchanges, but fails on a step I didn't modify. Guessing there is an issue with the container setup?

**Comment by gmmeyer** [comment]
Hey @wholroyd! Thank you very much for your contribution!

I think this probably makes sense as a new feature, however we're not going to be able to merge any more new features that are more than one or two lines before the next release. They take too much time to test, especially because we're in the middle of a changing the model for how we distribute and package the checks. I think we'd be pretty happy to add this change in after the next release, however.

Thank you very much, again! We do really appreciate it!

**Comment by irabinovitch** [comment]
@wholroyd Thank you for your efforts here. I know this has been a long time coming. 

As Greg mentioned we're currently migrating checks out this repo and into new https://github.com/DataDog/integrations-core and https://github.com/DataDog/integrations-extras. This change would fit into the https://github.com/DataDog/integrations-core repo.  The will enable a new release process that allows us to test, merge, and release integrations individually rather than waiting on a full dd-agent release. 

Would it be OK if we close this PR and and ask you to open a new one against the **[integrations-core](https://github.com/DataDog/integrations-core)** repository? 

We will be keeping a close eye on these repos and will be able to offer *much* quicker feedback on any PRs you submit. 

Additionally we have launched a new [community office hours](https://github.com/DataDog/dd-agent/wiki/Community-Office-Hours) during which our engineering and community teams will be available to perform code review and offer feedback on new and existing integration.

If you're around tomorrow at 10:30am PT we'd be happy to help you during office hours.

**Comment by wholroyd** [comment]
Just getting around to your messages. Yeah, I can resubmit to the other project.

**Comment by wholroyd** [comment]
Closing the PR and moved the change over to the new repo.

**Comment by bessey** [comment]
@wholroyd I see [no signs of the PR](https://github.com/DataDog/integrations-core/issues?utf8=%E2%9C%93&q=is%3Aissue%20rabbitmq) in the new repo. We exclusively use RabbitMQ for the exchanges so would really appreciate if this landed.

**Comment by gmmeyer** [comment]
@bessey it's here: https://github.com/DataDog/integrations-core/pull/176

**Pull request closed without merging**
