### PR TITLE
Testing oracle integration

### PR DESCRIPTION
**Pull request by handigarde**

### CODE REVIEW

**Comment by handigarde** [comment]
Adding a note for steps needed to allow access to `cx_Oracle` (will also be including in `oracle.yaml.example`).

To install `cx_Oracle` the following steps are needed:
```
# Download Oracle Instant Client (example dir: ~/oracle)
mkdir -p /opt/oracle/ && cd /opt/oracle/
unzip ~/oracle/instantclient-basic-linux.x64-12.1.0.2.0.zip
unzip ~/oracle/instantclient-sdk-linux.x64-12.1.0.2.0.zip

export LD_RUN_PATH=/opt/oracle/instantclient_12_1
export ORACLE_HOME=/opt/oracle/instantclient_12_1

/opt/datadog-agent/embedded/bin/pip install cx_Oracle
```

From this point the `LD_LIBRARY_PATH` on the host will need to point to `/opt/oracle/instantclient_12_1`  when starting/restarting the agent

**Comment by truthbk** [comment]
If you run into issues on this step: `/opt/datadog-agent/embedded/bin/pip install cx_Oracle` try the following: 

```
ln -sf /opt/oracle/instantclient_12_1/libclntsh.so.12.1 /opt/oracle/instantclient_12_1/libclntsh.so
ln -sf /opt/oracle/instantclient_12_1/libclntshcore.so.12.1 /opt/oracle/instantclient_12_1/libclntshcore.so
```

after creating these symlinks please try again.

**Comment by truthbk** [comment]
Hi @handigarde ,

Thanks again for your contribution, always very much appreciated. We're currently transitioning our checks to a new SDK-based model for the agent. An unfortunate side-effect is that we have to impose a freeze on the dd-agent repo. The SDK consists of two repositories https://github.com/DataDog/integrations-core and https://github.com/DataDog/integrations-extras, where all of our checks will reside. This PR would belong in the **[core](https://github.com/DataDog/integrations-core)** repository. Would you be so kind as to re-open the PR there? We have facilitated some tools to help you with the SDK development that should help you get up and running in no time: 
- [SDK guide](http://docs.datadoghq.com/guides/integration_sdk/) 
- [datadog SDK gem]( https://github.com/DataDog/datadog-sdk-testing). 

We are very sorry for the inconvenience caused. 

Thank you for your patience as we make this transition!

**Comment by truthbk** [comment]
@handigarde, I've taken the liberty of opening a PR here to help you transition to the SDK DataDog/integrations-extras#45

I created a patch with your work and dropped it that PR. Please feel free to continue your work there. 🙇

**Pull request closed without merging**
