### PR TITLE
[ssh_check] Support ECDSA ssh private key type closes #2481

### LINKED ISSUE #2481: Support ECDSA for ssh_check
ssh_check.py is not support ECDSA ssh key.
paramiko is support ECDSA ssh key.
http://docs.paramiko.org/en/1.17/api/keys.html#module-paramiko.ecdsakey

I changes ssh_key.py, but It's not working.

```
2016-05-08 17:56:27 JST | ERROR | dd.collector | checks.ssh_check(__init__.py:763) | Check 'ssh_check' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 746, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/ssh_check.py", line 70, in check
    password=conf.password, pkey=private_key)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/paramiko/client.py", line 307, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/paramiko/client.py", line 519, in _auth
    raise saved_exception
AuthenticationException: Authentication failed.
```

### PR DESCRIPTION
**Pull request by n0ts**
Hi, I add ssh_check support ECDSA key support. Add ssh_key configuration private_key_type, dump up version paramiko latest 1.15.x.

Regards,

### CODE REVIEW

**Comment by truthbk** [comment]
@n0ts, once again thank you for your work. We definitely want to support as many ciphers and key types as possible, we just need to make sure this plays well with our windows agent, and hopefully the `paramiko` version bump is a non-issue. We'll review and test accordingly and either give you feedback or merge this soon.

Thanks!

**Comment by n0ts** [comment]
@truthbk Thanks comment, I reverted `paramiko` version. I think that `paramiko` version is too old.

**Comment by truthbk** [comment]
@n0ts sorry it took us longer then it should've to review this change.... 

Yeah, we are on a bit of an older `paramiko` version. In part we had to stick to an older version due to a paramiko dependency on `ctypes` and a workaround we needed for our windows agent. Do you need version 2.0 for your changes?

On the other hand, we have a conflict with `master`. Could you please rebase your changes?

Thank you for your patience!

**Comment by n0ts** [comment]
@truthbk Thanks for your comment.
I merge from master.

And I have a no reason `paramiko` version up. I just think that `paramiko` version 1.15.2 is too old.

Thanks.

**Comment by n0ts** [comment]
@truthbk Hi, this RP will be release 5.10.0?

**Comment by degemer** [comment]
Closing, merged in https://github.com/DataDog/dd-agent/pull/2965, thanks @n0ts !

**Pull request closed without merging**
