### PR TITLE
redisdb: add replication service check and 'down since' metric

### PR DESCRIPTION
**Pull request by pbitty**
This add a service checks for redis slaves, which reports CRITICAL when the slave loses a link with the master.  It will also report the amount of seconds the link has been down.

### CODE REVIEW

**Comment by pbitty** [comment]
The service check is named `custom_check.redis.replication.master_link_status` for now.  With just the `redis` prefix, I could not create a monitor for it.  I've contacted support about the issue.

**Comment by remh** [comment]
Thanks a bunch a @pbitty  !

Our master branch is currently frozen for the preparation of our 5.2.0 release.

We'll review your pull request for our 5.3.0 release.
Thanks again!

**Comment by pbitty** [comment]
Thanks @remh .  I just added a time.sleep to the tests, to make sure some metrics can build up.  I had this in the tests but lost it on a rebase.

**Comment by remh** [comment]
@pbitty Could you merge the master branch back to your branch and fix the conflicts please ? We can't merge it as is.

Thanks a lot !

**Comment by remh** [comment]
Closing in favor of #1447 
Thanks a lot @pbitty !

**Comment by pbitty** [comment]
Thanks @remh.  Sorry for the late response.  I was on vacation with no internet connection at all.

**Pull request closed without merging**
