### PR TITLE
[system_swap] add example conf file

### PR DESCRIPTION
**Pull request by talwai**
This example file was previously missing

### CODE REVIEW

**Comment by yannmh** [comment]
Should this go with the 5.4 ?

**Comment by hkaj** [comment]
@yannmh yes it should. Otherwise no one will know how to run the system_swap check.

**Comment by talwai** [comment]
@yannmh ditto haissam - It was a mistake of mine to not include this in the original PR #1549

**Comment by hkaj** [comment]
You can :ship: it, I'm testing the check in the meantime

**Pull request merged**
